name: Env demo
on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  env_demo:
    env:
      APP_ENV: "test"
    runs-on: ubuntu-latest
    steps:
      - name: connecting to env
        env:
          APP_ENV: "prod"
        run: echo "App is connecting to $APP_ENV"
